/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BackofficeRouteImport } from './routes/backoffice'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackofficeStaffRouteImport } from './routes/backoffice.staff'
import { Route as BackofficeServicesRouteImport } from './routes/backoffice.services'
import { Route as BackofficeClientsRouteImport } from './routes/backoffice.clients'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeStaffRoute = BackofficeStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeServicesRoute = BackofficeServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeClientsRoute = BackofficeClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => BackofficeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/backoffice/clients': typeof BackofficeClientsRoute
  '/backoffice/services': typeof BackofficeServicesRoute
  '/backoffice/staff': typeof BackofficeStaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/backoffice/clients': typeof BackofficeClientsRoute
  '/backoffice/services': typeof BackofficeServicesRoute
  '/backoffice/staff': typeof BackofficeStaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/backoffice/clients': typeof BackofficeClientsRoute
  '/backoffice/services': typeof BackofficeServicesRoute
  '/backoffice/staff': typeof BackofficeStaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backoffice'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/backoffice/clients'
    | '/backoffice/services'
    | '/backoffice/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backoffice'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/backoffice/clients'
    | '/backoffice/services'
    | '/backoffice/staff'
  id:
    | '__root__'
    | '/'
    | '/backoffice'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/backoffice/clients'
    | '/backoffice/services'
    | '/backoffice/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackofficeRoute: typeof BackofficeRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/staff': {
      id: '/backoffice/staff'
      path: '/staff'
      fullPath: '/backoffice/staff'
      preLoaderRoute: typeof BackofficeStaffRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/services': {
      id: '/backoffice/services'
      path: '/services'
      fullPath: '/backoffice/services'
      preLoaderRoute: typeof BackofficeServicesRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/clients': {
      id: '/backoffice/clients'
      path: '/clients'
      fullPath: '/backoffice/clients'
      preLoaderRoute: typeof BackofficeClientsRouteImport
      parentRoute: typeof BackofficeRoute
    }
  }
}

interface BackofficeRouteChildren {
  BackofficeClientsRoute: typeof BackofficeClientsRoute
  BackofficeServicesRoute: typeof BackofficeServicesRoute
  BackofficeStaffRoute: typeof BackofficeStaffRoute
}

const BackofficeRouteChildren: BackofficeRouteChildren = {
  BackofficeClientsRoute: BackofficeClientsRoute,
  BackofficeServicesRoute: BackofficeServicesRoute,
  BackofficeStaffRoute: BackofficeStaffRoute,
}

const BackofficeRouteWithChildren = BackofficeRoute._addFileChildren(
  BackofficeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackofficeRoute: BackofficeRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
