/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BackofficeRouteImport } from './routes/backoffice'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as BackofficeIndexRouteImport } from './routes/backoffice.index'
import { Route as PortalBookRouteImport } from './routes/portal.book'
import { Route as BackofficeStaffRouteImport } from './routes/backoffice.staff'
import { Route as BackofficeSettingsRouteImport } from './routes/backoffice.settings'
import { Route as BackofficeServicesRouteImport } from './routes/backoffice.services'
import { Route as BackofficeReportsRouteImport } from './routes/backoffice.reports'
import { Route as BackofficeClientsRouteImport } from './routes/backoffice.clients'
import { Route as BackofficeAppointmentsRouteImport } from './routes/backoffice.appointments'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const BackofficeIndexRoute = BackofficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeRoute,
} as any)
const PortalBookRoute = PortalBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => PortalRoute,
} as any)
const BackofficeStaffRoute = BackofficeStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeSettingsRoute = BackofficeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeServicesRoute = BackofficeServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeReportsRoute = BackofficeReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeClientsRoute = BackofficeClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeAppointmentsRoute = BackofficeAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => BackofficeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/backoffice/appointments': typeof BackofficeAppointmentsRoute
  '/backoffice/clients': typeof BackofficeClientsRoute
  '/backoffice/reports': typeof BackofficeReportsRoute
  '/backoffice/services': typeof BackofficeServicesRoute
  '/backoffice/settings': typeof BackofficeSettingsRoute
  '/backoffice/staff': typeof BackofficeStaffRoute
  '/portal/book': typeof PortalBookRoute
  '/backoffice/': typeof BackofficeIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/backoffice/appointments': typeof BackofficeAppointmentsRoute
  '/backoffice/clients': typeof BackofficeClientsRoute
  '/backoffice/reports': typeof BackofficeReportsRoute
  '/backoffice/services': typeof BackofficeServicesRoute
  '/backoffice/settings': typeof BackofficeSettingsRoute
  '/backoffice/staff': typeof BackofficeStaffRoute
  '/portal/book': typeof PortalBookRoute
  '/backoffice': typeof BackofficeIndexRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/backoffice/appointments': typeof BackofficeAppointmentsRoute
  '/backoffice/clients': typeof BackofficeClientsRoute
  '/backoffice/reports': typeof BackofficeReportsRoute
  '/backoffice/services': typeof BackofficeServicesRoute
  '/backoffice/settings': typeof BackofficeSettingsRoute
  '/backoffice/staff': typeof BackofficeStaffRoute
  '/portal/book': typeof PortalBookRoute
  '/backoffice/': typeof BackofficeIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backoffice'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/profile'
    | '/reset-password'
    | '/backoffice/appointments'
    | '/backoffice/clients'
    | '/backoffice/reports'
    | '/backoffice/services'
    | '/backoffice/settings'
    | '/backoffice/staff'
    | '/portal/book'
    | '/backoffice/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/backoffice/appointments'
    | '/backoffice/clients'
    | '/backoffice/reports'
    | '/backoffice/services'
    | '/backoffice/settings'
    | '/backoffice/staff'
    | '/portal/book'
    | '/backoffice'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/backoffice'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/profile'
    | '/reset-password'
    | '/backoffice/appointments'
    | '/backoffice/clients'
    | '/backoffice/reports'
    | '/backoffice/services'
    | '/backoffice/settings'
    | '/backoffice/staff'
    | '/portal/book'
    | '/backoffice/'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackofficeRoute: typeof BackofficeRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof BackofficeIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/portal/book': {
      id: '/portal/book'
      path: '/book'
      fullPath: '/portal/book'
      preLoaderRoute: typeof PortalBookRouteImport
      parentRoute: typeof PortalRoute
    }
    '/backoffice/staff': {
      id: '/backoffice/staff'
      path: '/staff'
      fullPath: '/backoffice/staff'
      preLoaderRoute: typeof BackofficeStaffRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/settings': {
      id: '/backoffice/settings'
      path: '/settings'
      fullPath: '/backoffice/settings'
      preLoaderRoute: typeof BackofficeSettingsRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/services': {
      id: '/backoffice/services'
      path: '/services'
      fullPath: '/backoffice/services'
      preLoaderRoute: typeof BackofficeServicesRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/reports': {
      id: '/backoffice/reports'
      path: '/reports'
      fullPath: '/backoffice/reports'
      preLoaderRoute: typeof BackofficeReportsRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/clients': {
      id: '/backoffice/clients'
      path: '/clients'
      fullPath: '/backoffice/clients'
      preLoaderRoute: typeof BackofficeClientsRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/appointments': {
      id: '/backoffice/appointments'
      path: '/appointments'
      fullPath: '/backoffice/appointments'
      preLoaderRoute: typeof BackofficeAppointmentsRouteImport
      parentRoute: typeof BackofficeRoute
    }
  }
}

interface BackofficeRouteChildren {
  BackofficeAppointmentsRoute: typeof BackofficeAppointmentsRoute
  BackofficeClientsRoute: typeof BackofficeClientsRoute
  BackofficeReportsRoute: typeof BackofficeReportsRoute
  BackofficeServicesRoute: typeof BackofficeServicesRoute
  BackofficeSettingsRoute: typeof BackofficeSettingsRoute
  BackofficeStaffRoute: typeof BackofficeStaffRoute
  BackofficeIndexRoute: typeof BackofficeIndexRoute
}

const BackofficeRouteChildren: BackofficeRouteChildren = {
  BackofficeAppointmentsRoute: BackofficeAppointmentsRoute,
  BackofficeClientsRoute: BackofficeClientsRoute,
  BackofficeReportsRoute: BackofficeReportsRoute,
  BackofficeServicesRoute: BackofficeServicesRoute,
  BackofficeSettingsRoute: BackofficeSettingsRoute,
  BackofficeStaffRoute: BackofficeStaffRoute,
  BackofficeIndexRoute: BackofficeIndexRoute,
}

const BackofficeRouteWithChildren = BackofficeRoute._addFileChildren(
  BackofficeRouteChildren,
)

interface PortalRouteChildren {
  PortalBookRoute: typeof PortalBookRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBookRoute: PortalBookRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackofficeRoute: BackofficeRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
